package com.quartzy.qapi.command;

public enum ArgumentTypeEnum{
        BOOLEAN, FLOAT, DOUBLE, INTEGER, LONG, GAME_PROFILE, BLOCK_POS, COLUMN_POS, VEC3, VEC2, BLOCK_STATE, BLOCK_PREDICATE,
        MATERIAL, ITEM_PREDICATE, COLOR, COMPONENT, MESSAGE, MESSAGE_SELECTORS, NBT_COMPOUND_TAG, NBT_TAG, NBT_PATH, OBJECTIVE, OBJECTIVE_CRITERIA, OPERATION,
        PARTICLE, ANGLE, ROTATION, SCOREBOARD_SLOT, SCORE_HOLDER, SWIZZLE, TEAM, ITEM_SLOT, RESOURCE_LOCATION, MOB_EFFECT, FUNCTION, ENTITY_ANCHOR,
        ITEM_ENCHANTMENT, ENTITY_SUMMON, DIMENSION, TIME, UUID, STRING_WORD, STRING_GREEDY, PLAYER, PLAYERS, ENTITIES, ENTITY,
        STRING_STRING
}